inputs_def:
  - handle: pdf_path
    description: "%input-pdf-file2%"
    json_schema:
      type: string
      ui:widget: file
  - handle: output_path
    description: "%output-pdf-file-with-deleted-pages%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: PDF
            extensions:
              - pdf
  - handle: pages_to_delete
    description: "%pages-to-delete-e-g-1-3-5-7%"
    json_schema:
      type: string

outputs_def:
  - handle: output_path
    description: PDF file with deleted pages
    json_schema:
      type: string
      ui:widget: file
  - handle: pages_deleted
    description: Number of pages deleted
    json_schema:
      type: number
  - handle: remaining_pages
    description: Number of remaining pages
    json_schema:
      type: number

executor:
  name: python
  options:
    spawn: false
    entry: __init__.py

title: "%pdf-delete-pages%"
icon: ":carbon:delete:"
description: "%remove-specific-pages-from-pdf-files%"

ui:
  default_width: 450
