inputs_def:
  - handle: pdf_path
    description: "%input-pdf-file-to-encrypt%"
    json_schema:
      type: string
      ui:widget: file
  - handle: output_path
    description: "%output-encrypted-pdf-file%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: PDF
            extensions:
              - pdf
  - handle: user_password
    description: "%user-password-for-opening-the-pdf%"
    json_schema:
      type: string
  - handle: owner_password
    description: "%owner-password-for-permissions%"
    json_schema:
      type: string
    nullable: true
  - group: "Permissions"
    collapsed: true
  - handle: allow_printing
    description: "%allow-printing%"
    json_schema:
      type: boolean
    value: true
  - handle: allow_copying
    description: "%allow-copying-text%"
    json_schema:
      type: boolean
    value: true
  - handle: allow_modification
    description: "%allow-document-modification%"
    json_schema:
      type: boolean
    value: false

outputs_def:
  - handle: output_path
    description: Encrypted PDF file path
    json_schema:
      type: string
      ui:widget: file

executor:
  name: python
  options:
    spawn: false
    entry: __init__.py

title: "%pdf-encrypt%"
icon: ":carbon:locked:"
description: "%password-protect-pdf-files-with-encryption%"

ui:
  default_width: 617.610018733854
