inputs_def:
  - handle: pdf_path
    description: "%input-encrypted-pdf-file%"
    json_schema:
      type: string
      ui:widget: file
  - handle: output_path
    description: "%output-decrypted-pdf-file%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: PDF
            extensions:
              - pdf
  - handle: password
    description: "%password-to-decrypt-the-pdf%"
    json_schema:
      type: string

outputs_def:
  - handle: output_path
    description: "%decrypted-pdf-file-path%"
    json_schema:
      type: string
      ui:widget: file
  - handle: was_encrypted
    description: "%whether-the-pdf-was-encrypted%"
    json_schema:
      type: boolean

executor:
  name: python
  options:
    spawn: false
    entry: __init__.py

title: "%pdf-decrypt%"
icon: ":carbon:unlocked:"
description: "%remove-password-protection-from-encrypted-pdf-files%"

ui:
  default_width: 450
