executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: pdf
    description: "%input-pdf-file-to-extract-metadata-from%"
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: name
    description: PDF document name
    json_schema:
      type: string
  - handle: meta
    description: PDF metadata information
    json_schema:
      type: object
      additionalProperties:
        type: string
title: "%pdf-to-meta%"
icon: ":carbon:data-enrichment-add:"
description: "%extract-metadata-and-document-information-from-pdf-files%"
