inputs_def:
  - handle: input_source
    description: "%input-source-type%"
    json_schema:
      type: string
      enum:
        - "html_file"
        - "html_string"
        - "url"
    value: html_file
  - handle: html_file
    description: "%html-file-to-convert%"
    json_schema:
      type: string
      ui:widget: file
    nullable: true
  - handle: html_string
    description: "%html-string-to-convert%"
    json_schema:
      type: string
    nullable: true
  - handle: url
    description: "%url-to-convert-to-pdf%"
    json_schema:
      type: string
    nullable: true
  - handle: output_path
    description: "%output-pdf-file%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: PDF
            extensions:
              - pdf
  - handle: page_size
    description: "%page-size%"
    json_schema:
      type: string
      enum:
        - "A4"
        - "A3"
        - "A5"
        - "Letter"
        - "Legal"
    value: A4
  - handle: orientation
    description: "%page-orientation%"
    json_schema:
      type: string
      enum:
        - "portrait"
        - "landscape"
    value: portrait
  - handle: margin_top
    description: "%top-margin-mm%"
    json_schema:
      type: number
      minimum: 0
    value: 20
  - handle: margin_bottom
    description: "%bottom-margin-mm%"
    json_schema:
      type: number
      minimum: 0
    value: 20
  - handle: margin_left
    description: "%left-margin-mm%"
    json_schema:
      type: number
      minimum: 0
    value: 20
  - handle: margin_right
    description: "%right-margin-mm%"
    json_schema:
      type: number
      minimum: 0
    value: 20

outputs_def:
  - handle: output_path
    description: Generated PDF file path
    json_schema:
      type: string
      ui:widget: file

executor:
  name: python
  options:
    spawn: false
    entry: __init__.py

title: "%html-to-pdf%"
icon: ":carbon:html:"
description: "%convert-html-content-or-web-pages-to-pdf-format%"

ui:
  default_width: 450
