inputs_def:
  - handle: pdf_path
    description: "%input-pdf-file3%"
    json_schema:
      type: string
      ui:widget: file
  - handle: watermark_text
    description: "%watermark-text-leave-empty-for-image-watermark%"
    json_schema:
      type: string
    value:
    nullable: true
  - handle: watermark_image
    description: "%watermark-image-file%"
    json_schema:
      type: string
      ui:widget: file
    value:
    nullable: true
  - handle: output_path
    description: "%output-pdf-file-path2%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: PDF
            extensions:
              - pdf
    value:
    nullable: true
  - group: "Position & Layer"
    collapsed: true
  - handle: position_x
    description: "%watermark-x-position-0-1-0-left-1-right%"
    json_schema:
      type: number
      minimum: 0
      maximum: 1
      default: 0.5
    value: null
    nullable: true
  - handle: position_y
    description: "%watermark-y-position-0-1-0-bottom-1-top%"
    json_schema:
      type: number
      minimum: 0
      maximum: 1
      default: 0.5
    value: null
    nullable: true
  - handle: layer
    description: "%watermark-layer-background-or-foreground%"
    json_schema:
      type: string
      enum:
        - background
        - foreground
      default: background
    value: null
    nullable: true
  - group: "Styling Options"
    collapsed: true
  - handle: opacity
    description: "%watermark-opacity-0-1-0-transparent-1-opaque%"
    json_schema:
      type: number
      minimum: 0
      maximum: 1
      default: 0.15
    value: null
    nullable: true
  - handle: font_size
    description: "%font-size-for-text-watermark%"
    json_schema:
      type: number
      minimum: 8
      maximum: 72
      default: 36
    value: null
    nullable: true
  - handle: rotation
    description: "%watermark-rotation-angle-degrees%"
    json_schema:
      type: number
      minimum: -180
      maximum: 180
      default: 45
    value: null
    nullable: true
  - handle: color
    description: "%text-watermark-color%"
    json_schema:
      type: string
      ui:widget: color
      ui:options:
        colorType: HEX
      default: "#B8B8B8"
    value: null
    nullable: true

outputs_def:
  - handle: output_path
    description: Watermarked PDF file path
    json_schema:
      type: string
      ui:widget: file

executor:
  name: python
  options:
    spawn: false
    entry: __init__.py

title: "%pdf-watermark%"
icon: ":carbon:checkmark-outline:"
description: "%add-text-or-image-watermarks-to-pdf-files%"

ui:
  default_width: 450
