inputs_def:
  - handle: pdf_path
    description: "%input-pdf-file-to-rotate%"
    json_schema:
      type: string
      ui:widget: file
    value: /oomol-driver/oomol-storage/pdf/page_range_1_1-100.pdf
  - handle: output_path
    description: "%output-rotated-pdf-file%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: PDF
            extensions:
              - pdf
    value: /oomol-driver/oomol-storage/pdf/pdfeee.pdf
  - handle: rotation_angle
    description: "%rotation-angle-in-degrees%"
    json_schema:
      type: string
      enum:
        - "90"
        - "180"
        - "270"
      ui:options:
        labels:
          - "90"
          - "180"
          - "270"
    value: "90"
  - handle: page_range
    description: "%pages-to-rotate-e-g-1-3-5-7-9-or-all%"
    json_schema:
      type: string
    value: all

outputs_def:
  - handle: output_path
    description: Rotated PDF file path
    json_schema:
      type: string
      ui:widget: file
  - handle: pages_rotated
    description: Number of pages rotated
    json_schema:
      type: number

executor:
  name: python
  options:
    spawn: false
    entry: __init__.py

title: "%pdf-rotate%"
icon: ":carbon:rotate-clockwise:"
description: "%rotate-pdf-pages-by-specified-angles%"

ui:
  default_width: 450
